In [2]:
import numpy as np
list = [[1,2,3],[4,5,6]]
arr2d = np.array(list)
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr2d.size

6

In [5]:
arr2d.shape  

(2, 3)

In [6]:
arr2d.ndim

2

In [7]:
arr2d.itemsize

8

In [8]:
arr2d.dtype

dtype('int64')

In [9]:
arr_float = arr2d.astype(np.float32)
arr_float

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [13]:
arr_fourbyfive = _1st = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]]
arr_fourbyfive = np.array(arr_fourbyfive,dtype='float32')
arr_fourbyfive

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.]], dtype=float32)

In [17]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.diag((2,2))

array([[2, 0],
       [0, 2]])

In [21]:
np.random.rand(3,4)

array([[0.62631692, 0.85079772, 0.78808445, 0.29238427],
       [0.55840927, 0.26574798, 0.51223676, 0.68272372],
       [0.37487159, 0.12078561, 0.55162083, 0.90719463]])

In [22]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [26]:
np.arange(7,10)

array([7, 8, 9])

In [27]:
np.arange(1,9,2)

array([1, 3, 5, 7])

In [29]:
np.linspace(0.,1.,num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [33]:
np.arange(1,40,2)    #odd no. between 0 to 40

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [36]:
arr_ind=np.array([1,2,3])
arr_ind

array([1, 2, 3])

In [37]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
arr2d[0, :2]

array([1, 2])

In [39]:
arr_fourbyfive    #it was defined earlier

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.]], dtype=float32)

In [40]:
arr_fourbyfive[2, :]      #access row

array([11., 12., 13., 14., 15.], dtype=float32)

In [41]:
arr_fourbyfive[:,2]       #access a column

array([ 3.,  8., 13., 18.], dtype=float32)

In [44]:
arr_fourbyfive[:,:3]     #access first 3 column

array([[ 1.,  2.,  3.],
       [ 6.,  7.,  8.],
       [11., 12., 13.],
       [16., 17., 18.]], dtype=float32)

In [46]:
arr_fourbyfive[:2, :]        #access first 2 rows

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]], dtype=float32)

In [52]:
arr_fourbyfive[:3, :4]  #access first 3 rows and 4 column

array([[ 1.,  2.,  3.,  4.],
       [ 6.,  7.,  8.,  9.],
       [11., 12., 13., 14.]], dtype=float32)

In [65]:
arr_fourbyfive[::-1,::-1]      #reverse

array([[20., 19., 18., 17., 16.],
       [15., 14., 13., 12., 11.],
       [10.,  9.,  8.,  7.,  6.],
       [ 5.,  4.,  3.,  2.,  1.]], dtype=float32)

In [75]:
arr_fourbyfive[:,-1] 

array([ 5., 10., 15., 20.], dtype=float32)

In [76]:
arr2d=np.array([[1,2,3],[4,5,6]])
print(np.add(arr2d,4))
arr2d

[[ 5  6  7]
 [ 8  9 10]]


array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
print(np.subtract(arr2d,2))

[[-1  0  1]
 [ 2  3  4]]


In [79]:
print(arr_fourbyfive*4)

[[ 4.  8. 12. 16. 20.]
 [24. 28. 32. 36. 40.]
 [44. 48. 52. 56. 60.]
 [64. 68. 72. 76. 80.]]


In [80]:
arr2d **2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [81]:
new_arr = np.array([[1,2,3],[4,5,6]])
np.add.reduce(new_arr)
                

array([5, 7, 9])

In [82]:
np.add.reduce(new_arr, axis=1)

array([ 6, 15])

In [86]:
arr3d = np.array([1,2,4])+1
arr3d

array([2, 3, 5])

In [91]:
#reshaping an array

arr1d=np.array([4,5,6,8,7,45,89,6,7,6,8,9])
arr4d_view=arr1d.reshape(3,4)
arr4d_view

array([[ 4,  5,  6,  8],
       [ 7, 45, 89,  6],
       [ 7,  6,  8,  9]])

In [94]:
arr4d_view.ravel()

array([ 4,  5,  6,  8,  7, 45, 89,  6,  7,  6,  8,  9])

NameError: name 'plt' is not defined